### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by mkearney** [williamaeberhard/glmrob.nb#2]
Any updates on this function? i.e., any additional testing/validation, movement/integration into robust or other R pkg, or development of any other/extended versions?

**Comment by williamaeberhard** [comment]
I haven't touched it in a while, v0.4 is still the latest release. No plans to move it to robust/robustbase or other R packages yet, I haven't received that many requests regarding this.

Regarding extensions, I only am aware of an adaptation of `glmrob.nb` for an identity link function, see [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5346680/). Also, I have the robNB package which focuses more on tests on coefficients. Please feel free to share any suggestion.

**Comment by tdelhomme** [comment]
Hi all,
concerning [our paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5346680/), the code of the adapted function is available [here](https://github.com/IARCbioinfo/needlestack/blob/master/bin/glm_rob_nb.r), we can provide more details if needed.
